### ISSUE TITLE
Can't run scribe tests

### ISSUE THREAD

**Issue by cutandpastey** [guardian/scribe#310]
On a fresh checkout I can't run the test suite.  I get this output:

Uncaught NoSuchElementError: no such element

I followed the instructions within https://github.com/guardian/scribe/blob/master/CONTRIBUTING.md

@theefer @rrees any ideas?

**Comment by theefer** [comment]
Works for me. I'm afraid it's a little hard to diagnose remotely...

Can @robinedman and @hmgibson23 run the tests?

**Comment by robinedman** [comment]
Did a fresh checkout to try it out. Getting the same error....

**Comment by robinedman** [comment]
Seems to be nginx using port 8080

**Comment by theefer** [comment]
Ah.

On fresh checkout I got

```
  1)  "before all" hook:
     Uncaught UnknownError: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
      at new bot.Error (/home/seb/work/scribe-fresh/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
      at Object.bot.response.checkResponse (/home/seb/work/scribe-fresh/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
```

Copying the chromedriver binary to the project root folder fixed the error.

I don't have anything running on 8080 initially. If I get another process on 8080, I then get a clear error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3


  block mode
    given default content
      when the user types
        1) "before each" hook
        2) "after each" hook


  0 passing (7s)
  2 failing

  1)  "before each" hook:
     NoSuchWindowError: no such window: target window already closed
...
```

**Comment by cutandpastey** [comment]
As @robinedman says, it was a port issue here, I'm updating docs to account for this. Weird that @theefer gets that error, I get no `EADDRINUSE`.
