### ISSUE TITLE
Firefox: NS_ERROR_FAILURE when refreshing page

### ISSUE THREAD

**Issue by jamespamplin** [guardian/scribe#435]
A page with Scribe and `scribe-plugin-toolbar` will throw a `NS_ERROR_FAILURE` error when the scribe element is focussed and the page is refreshed on Firefox.

```
NS_ERROR_FAILURE:
 at CommandPatch.prototype.queryState@http://guardian.github.io/scribe/bower_components/scribe/scribe.js:6655:14
 at updateUi@http://guardian.github.io/scribe/bower_components/scribe-plugin-toolbar/scribe-plugin-toolbar.js:49:34
```

```
NS_ERROR_FAILURE:
 at Command.prototype.queryState@http://guardian.github.io/scribe/bower_components/scribe/scribe.js:6691:16
 at updateUi@http://guardian.github.io/scribe/bower_components/scribe-plugin-toolbar/scribe-plugin-toolbar.js:49:34
```

Appears to be caused by `document.queryCommandState` throwing the error for each toolbar element when the page is refreshed.

**Comment by rrees** [comment]
@jamespamplin yeah there are a number of Firefox focus issues. Do you think there is way of detecting and correcting the focus in code?

**Comment by jamespamplin** [comment]
I caught `NS_ERROR_UNEXPECTED` errors with a try catch in #406 before. Was thinking of wrapping `document.queryCommandState` in a try catch for this specific error.
